[build]
command = "npm run build"
publish = "dist"
edge_functions = "netlify/edge-functions"

[dev]
command = "npm run dev"
targetPort = 5173
port = 8888
publish = "dist"
edge_functions = "netlify/edge-functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 